### ISSUE TITLE
Github Actions doesn't fail on STOP

### ISSUE THREAD

**Issue by scrasmussen** [NCAR/icar#132]
## Expected Behavior
If `icar` executable exits with `STOP` the github action action should fail.

## Current Behavior
Looking at a recent [github actions report](https://github.com/NCAR/icar/runs/6873467001?check_suite_focus=true) and clicking on `Execute Test Run`, one can see that the action is reporting `success` when it should be a `failure`.

Section of `Execute Test Run` output  in `build_and_test_ICAR` shows
```
 Initializing Options
STOP Options file does not exist. 
 Using options file = icar_options.nm
```
which reports
``` 
build_and_test_ICAR
succeeded 15 days ago in 12m 23
```

## Possible Solution
Unsure, working on it now.

## Steps to Reproduce (for bugs)

1. Looked at Github Actions report, unsure behavior when testing locally.

**Comment by gutmann** [comment]
#134 fixes this
