### ISSUE TITLE
iterative wind solver and wind rotation parallel bug

### ISSUE THREAD

**Issue by gutmann** [NCAR/icar#146]
Both the iterative wind solver and the wind rotation to the grid appear to have minor errors that change the windfield when run in parallel relative to the value when run in serial.  Setting a larger halo size (3) fixes this, but with a very large computational cost.  

## Expected Behavior
wind fields are the same in serial and parallel

## Current Behavior
difference between serial and parallel wind fields appear between processes.

## Possible Solution
increase size of u and v grids to provide more information outside of immediate boundary, without increasing the halo being passed in all variables. 

## Steps to Reproduce (for bugs)
1. cafrun -np 36 icar
2. cafrun -np 1 icar
3. difference output files

## Your Environment
* Version of the code used: latest develop (pre 2.1 release)
* Operating System and version: linux
* Compiler and version: gfortran 10.1 opencoarrays 2.9.2

**Comment by scrasmussen** [comment]
Closed by PR #149
