### ISSUE TITLE
Helper scripts have missing dependencies

### ISSUE THREAD

**Issue by wundersooner** [NCAR/icar#18]
The helper scripts are doing some imports from python modules I can't find.  The culprits are
stat_down
mygis
load_data

**Comment by gutmann** [comment]
Thanks, I've been meaning to clean up the dependencies at some point, I'll see if I can get those in tomorrow. 

Ethan

**Comment by gutmann** [comment]
see if #19 fixes this for you.  The mygis package was already present in the "develop" branch, stat_down.io was really just an old version of mygis, and load_data is now added as well.  These are in the lib/ directory.  This whole thing should be turned into an easy_install package or the like, but for now, at least all dependencies may be present. 

I'll merge #19 into the develop branch in a second once the CI build completes.

**Comment by gutmann** [comment]
I'm going to close, feel free to reopen or add a new issue if you find another missing dependency, or otherwise have problems with these.
