### ISSUE TITLE
Linear_wind_LUT.nc created every time

### ISSUE THREAD

**Issue by kbnd** [NCAR/icar#26]
I've tried assigning the absolute and relative path for `LUT_filename` in the namelist file, but when `read_LUT = True` and `write_LUT = False`, ICAR still creates a linear theory LUT. I'm using the same hi res file (domain) every time. I also tried commenting `write_LUT`, but it still created the LUT.

**Comment by gutmann** [comment]
I'm not sure I quite understand what is happening.  It has to create the LUT in memory, but it shouldn't write the file if write_LUT is false.  Are you sure it is reading the namelist you have edited?  When it writes the LUT to disk, does it print anything to the screen?  

The relevant code is here: https://github.com/NCAR/icar/blob/master/physics/linear_winds.f90#L991
```if ((options%lt_options%write_LUT).and.(.not.reverse)) then
  if ((options%lt_options%read_LUT) .and. (error == 0)) then
    print*, "Not writing Linear Theory LUT to file because LUT was read from file"
  else
    print*, "Writing Linear Theory LUT to file: ", trim(options%lt_options%u_LUT_Filename)
    error = write_LUT(options%lt_options%u_LUT_Filename, hi_u_LUT, hi_v_LUT, options%dz_levels, options%lt_options)
  endif
endif
```

**Comment by gutmann** [comment]
Or do you just mean that it is recomputing the LUT even when it should be reading it from disk?  It should print out some information if it is or is not able to read the LUT. Do you get such an error message? 

see https://github.com/NCAR/icar/blob/master/physics/linear_winds.f90#L903

```
  print*, "Reading LUT from file: ", trim(options%lt_options%u_LUT_Filename)
  error = read_LUT(options%lt_options%u_LUT_Filename, hi_u_LUT, hi_v_LUT, options%dz_levels, LUT_dims, options%lt_options)
  if (error/=0) then
    write(*,*) "WARNING: LUT on disk does not match that specified in the namelist or does not exist."
    write(*,*) "    LUT will be recreated"
```

**Comment by kbnd** [comment]
I have attached a log and my namelist of the icar run. ICAR was compiled using MODE=debug. I think the error at the end might have to do with the compile option as just using 'make' results in a failed build, but 'make MODE=debug'  is successful.

[cfs_icar_options.nml.txt](https://github.com/NCAR/icar/files/1145236/cfs_icar_options.nml.txt)

[icar_log.txt](https://github.com/NCAR/icar/files/1145235/icar_log.txt)

**Comment by gutmann** [comment]
ah, this probably isn't as clear as it should be.  Many of the namelists are not even read if you dont' set the corresponding "use_X_options" to true in the main parameter namelist.  In this case, you need to set use_lt_options=true so that it will read the options related to linear theory. 

https://github.com/NCAR/icar/blob/master/run/complete_icar_options.nml#L164

**Comment by kbnd** [comment]
It would help if I read every line of the full options namelist. Maybe I will add this to the docs or FAQ
