### ISSUE TITLE
compile ICAR

### ISSUE THREAD

**Issue by zxh163404** [NCAR/icar#45]
I had problem with compiling ICAR with gfortran, and I have tried gfortran (GCC) of version 4.4.7 and version 4.9.4, but both give error either like: 
f951: error: unrecognized command line option "-fno-protect-parens" 
make: *** [build/icar_constants.o] Error 1

or like:
"collect2: error: ld returned 1 exit status"
make: *** [build/icar_constants.o] Error 1

**Comment by gutmann** [comment]
You can safely remove "-fno-protect-parens" from the makefile, it is only a small optimization and must not be supported by earlier versions of gcc.  That said, you might be better off updating to a more recent version of gcc/gfortran.
