### ISSUE TITLE
Interpolation/triangulation error

### ISSUE THREAD

**Issue by wrzesien** [NCAR/icar#49]
When using WRF output (27 km as low res, 9 km as high res) as forcing data for ICAR, I get the following error:
 
Initializing Boundaries
Interpreting geopotential height as residing between model layers
   Setting up domain geographic Look Up Tables
ERROR finding triangle
          39          39          38          38
          61          60          61          60
   33.12846       238.2691    
   33.35105       238.3338    
   33.14337       238.4846    
   33.22448       238.0857    
   33.01720       238.2369    
 ERROR: Point not located in bounding triangle
   238.2691       33.12846    
 Triangle vertices
   238.3338       33.35105    
   238.4846       33.14337    
   238.2852       33.18402    
 -0.3326202      2.0896307E-04   1.332411    
 Point in poly returns: F
Triangulation is broken

**Comment by gutmann** [comment]
#50 should fix this.  As soon as the automated build system passes I will merge this into develop.

**Comment by gutmann** [comment]
I believe this is fixed in develop, closing.  Feel free to re-open if this appears again.
