### ISSUE TITLE
running icar issue

### ISSUE THREAD

**Issue by liuppei** [NCAR/icar#71]
When I run icar，There was a issue. I don't know how to solve it. It is like this:

Initializing Options
 Using options file = short_icar_options.nml
   Model version: 1.0.1

 Initializing Domain

 Initializing Boundaries
 Interpreting geopotential height as residing between model layers
   Setting up domain geographic Look Up Tables
 ERROR: Failed to find point   97.3592224       24.5479889      in a quadrant near:
   97.6912231       24.6180420
           1           1
         109         109

**Comment by gutmann** [comment]
Hi Liuppei, 
This could be one of two things 1) your forcing data don't completely cover your ICAR model domain, or 2) a bug in the geographic interpolation code that though I'd fixed but seems to keep reappearing in subtly different ways.  Can you confirm that your forcing data has grid cells in it South of 24.5N and West of 97.3E?

**Comment by gutmann** [comment]
see #68

**Comment by gutmann** [comment]
closing for now, if this is still an issue, let me know.
