### ISSUE TITLE
Compilation error for domain_obj.f90

### ISSUE THREAD

**Issue by sebastian-mutz** [NCAR/icar#75]
Hi Ethan

Compiling the latest icar-v2 (with fftw-3.3.8, libsz-2.1.1, hdf5-1.12.0, netcdf-c-4.7.4, netcdf-fortran-4.5.3), with the gfortran-10 compiler and CAF_MODE=single flag, I get the following error:

> 10 | submodule(domain_interface) domain_implementation
>      |                                           1
> ......
>  16 |     use io_routines,          only : io_read, io_write
>       |                                                            2
> Error: Symbol ‘io_read’ at (1) conflicts with the symbol at (2)

Could it be that io_read is already defined, so it creates this conflict here?
(1 ist at domain_interface, 2 at io_read)

Best wishes
Sebastian

**Comment by gutmann** [comment]
Thanks Sebastian, I’ll look into this today.  My first guess is that gfortran 10 changed the rules on what happens if sub-modules and modules import use another module (this code has compiled fine for me with gfortran 6,7,8, & 9… but I haven’t tested 10 yet, I feel like I’ve seen something like this before.

**Comment by sebastian-mutz** [comment]
Hi Ethan, if it helps: I quickly tried to compile it with gfortran-9 and got the same error. (I did not recompile dependencies however)

**Comment by gutmann** [comment]
Weird, this was working fine, I just loaded a few different versions and was able to reproduce this now.  It was using io_read in both the submodule and the parent module.  I don't think it used to complain about this, but it does now, so I'm pushing a fix.

**Comment by gutmann** [comment]
should be fixed by #76 let me know if you have any more problems.

**Comment by sebastian-mutz** [comment]
Thanks. It compiles fine with the declaration simply removed.
